version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mytestapp_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: mytestapp_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://myuser:mypass@db:5432/mydatabase
      API_KEY: mysecretkey
    depends_on:
      - db

volumes:
  postgres_data:
